import { auth,db,storage,collection,addDoc,query,orderBy,onSnapshot,ref,uploadBytes,getDownloadURL,onAuthStateChanged } from "./firebase.js";
const userDisplay=document.getElementById("user-display"),listingsContainer=document.getElementById("listings-container"),listingForm=document.getElementById("listing-form"),searchInput=document.getElementById("search-input"); let allListings=[];
const esc=v=>String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;");
function render(items){if(!listingsContainer)return;listingsContainer.innerHTML="";if(!items.length){listingsContainer.innerHTML='<div class="no-results-box">No listings match your search.</div>';return;}items.forEach(({id,data})=>{const c=document.createElement("article");c.className="listing-card";const img=data.imageUrl?`<img src="${esc(data.imageUrl)}" class="listing-image" alt="${esc(data.title||"Listing image")}">`:'<div class="listing-no-image">No image uploaded</div>';c.innerHTML=`${img}<div class="listing-card-content"><div class="listing-card-heading"><h3>${esc(data.title||"Untitled Listing")}</h3><span class="listing-price">$${Number(data.price||0).toFixed(2)}</span></div><p>${esc(data.desc||"No description provided.")}</p><p class="tags">Tags: ${esc(Array.isArray(data.tags)?data.tags.join(", "):(data.tags||"None"))}</p>${data.location?`<p><strong>Location:</strong> ${esc(data.location)}</p>`:""}<small>Posted by: ${esc(data.seller||"Unknown seller")}</small></div>`;c.onclick=()=>location.href=`product.html?id=${encodeURIComponent(id)}`;listingsContainer.appendChild(c);});}
function filter(){const t=(searchInput?.value||"").trim().toLowerCase();render(!t?allListings:allListings.filter(({data})=>[data.title,data.desc,data.location,data.seller,...(Array.isArray(data.tags)?data.tags:[data.tags])].filter(Boolean).join(" ").toLowerCase().includes(t)));}
function storageError(e){const code=e?.code||"unknown",m=(e?.message||"").toLowerCase();if(code.includes("unauthorized")||code.includes("unauthenticated"))return "Firebase Storage rejected the upload. Check Storage Security Rules for listingImages/{uid}/...";if(m.includes("cors")||m.includes("preflight"))return "Firebase Storage CORS blocked the browser preflight. Apply the supplied cors.json to your bucket.";if(m.includes("network")||code.includes("storage/unknown"))return "The Storage request could not complete. Check the Blaze plan, bucket name, CORS configuration, and Storage rules.";return `${e?.message||"Unknown error"}\n\nFirebase error code: ${code}`;}
async function uploadImage(file,user){if(!file)return null;if(!file.type.startsWith("image/"))throw new Error("Please select an image file.");if(file.size>10*1024*1024)throw new Error("Please choose an image smaller than 10 MB.");const name=file.name.replace(/[^a-zA-Z0-9._-]/g,"_");const r=ref(storage,`listingImages/${user.uid}/${Date.now()}-${name}`);console.log("Uploading image to:",r.fullPath);await uploadBytes(r,file,{contentType:file.type,cacheControl:"public,max-age=3600"});return getDownloadURL(r);}
onAuthStateChanged(auth,user=>{if(!user&&location.pathname.includes("products.html"))location.replace(`login.html?returnTo=${encodeURIComponent("products.html")}`);if(user&&userDisplay)userDisplay.textContent=user.email||"";});
searchInput?.addEventListener("input",filter);
listingForm?.addEventListener("submit",async e=>{e.preventDefault();const user=auth.currentUser;if(!user){location.href=`login.html?returnTo=${encodeURIComponent("products.html")}`;return;}const b=listingForm.querySelector('button[type="submit"]'),file=document.getElementById("item-image")?.files?.[0]||null;try{b.disabled=true;b.textContent=file?"Uploading...":"Posting...";const imageUrl=await uploadImage(file,user);b.textContent="Saving...";await addDoc(collection(db,"listings"),{title:document.getElementById("item-title").value.trim(),price:Number(document.getElementById("item-price").value),desc:document.getElementById("item-desc").value.trim(),tags:document.getElementById("item-tags").value.toLowerCase().split(",").map(x=>x.trim()).filter(Boolean),imageUrl,owner:user.uid,seller:user.email,location:document.getElementById("item-location").value.trim(),contact:document.getElementById("item-contact").value.trim(),payment:document.getElementById("item-payment").value.trim(),createdAt:Date.now()});listingForm.reset();alert("Listing posted successfully!");}catch(e){console.error("LISTING ERROR:",e);alert(file?"The image upload failed.\n\n"+storageError(e):"Error adding listing.\n\n"+e.message);}finally{b.disabled=false;b.textContent="Post Item";}});
if(listingsContainer){const q=query(collection(db,"listings"),orderBy("createdAt","desc"));onSnapshot(q,s=>{allListings=s.docs.map(d=>({id:d.id,data:d.data()}));render(allListings)},e=>{listingsContainer.innerHTML=`<div class="error-box"><strong>${esc(e.code||"Unknown error")}</strong><br><br>${esc(e.message)}</div>`});}
